# Generated by Django 4.1.7 on 2023-03-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houselog', '0002_alter_houselog_last_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselog',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
